### ISSUE TITLE
Fix confirmation step to not consume user input entered earlier

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#194] opened 2022-05-25 20:42 UTC
User need to confirm the SC deployment transaction sending. 
But currently, during the SC deployment data entry invitation step, if user will answer anything other than `yes` the SC deployment will be canceled.
Which is not good just because verification key generation is spread within the time and during those 1-2 mins users can, even accidentally, input some keystrokes like `<Enter>`, which, again, will result in SC deployment cancelation but time was spent to calculate verification key and user will have to start over.
```
zk deploy local
✔ Build project
✔ Generate build.json
✔ Choose smart contract
  The 'Add' smart contract will be used
  for this network as specified in config.json.
⠋ Generate verification key (takes 1-2 min)...
✔ Generate verification key (takes 1-2 min)
✔ Build transaction
✖ Confirm to send transaction

  ┌────────────────┬───────────────────────────────┐
  │ Network        │ local                         │
  ├────────────────┼───────────────────────────────┤
  │ Url            │ http://localhost:4006/graphql │
  ├────────────────┼───────────────────────────────┤
  │ Smart Contract │ Add                           │
  └────────────────┴───────────────────────────────┘

  Are you sure you want to send (yes/no)? · test
  Aborted. Transaction not sent.
```
It will be good to repeat the data enter invitation like `Are you sure you want to send (yes/no)?` until user won't explicitly enter `yes`, `no` or terminate the process.

**Comment by jasongitmail** [comment] 2022-05-25 21:10
Good catch.

The verification key generation with SnarkyJS is not ideal right now and needs to be reworked when time allows, but it won't be easy. But we should look into if this can be addressed in the CLI.

I reproduced: 
- `zk deploy qanet`
- When it gets to the verification key generation step, type 'yes' while it's still building the verification key
- When it proceeds onward, it will have accepted `yes` as input to the final confirmation step for sending the tx and will send the tx immediately.

**Comment by mitschabaude** [comment] 2022-05-26 08:59
@jasongitmail this would also be fixed by separating the `compile` and `deploy` steps, as proposed here: https://github.com/o1-labs/zkapp-cli/issues/158

**Comment by mitschabaude** [comment] 2022-05-26 09:01
Verification key generation in snarkyjs with Izzy's performance improvements will take less than a minute, but more than 10 seconds. I don't think there's a way to avoid it taking long if we don't separate it from the deploy step

**Comment by shimkiv** [comment] 2022-05-26 09:58
We don't really need to avoid an issue, the fix might be just to repeat input if received data from user != `yes` or `no`.

**Comment by jasongitmail** [comment] 2022-05-26 15:25
I think we should hesitate to split them apart because it'd be detrimental to the dev experience--creates two steps and the possibility of forgetting it and deploying something old...unless we're checking if it's old which then becomes similar to just caching the verification key during deployment.

**Comment by jasongitmail** [comment] 2022-08-01 14:33
Note to implementer: it may not be possible to fix this just based on how we use yargs. If that proves to be the case, creating a minimal reproduction and an issue on the yargs repo may be the way forward.

**Closed** 2022-10-11 04:16 UTC
Labels: bug, enhancement, P1
